# Generated by Django 5.1.3 on 2024-11-06 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_status', models.CharField(max_length=120, verbose_name='name_status')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_project', models.CharField(max_length=120, verbose_name='name_project')),
                ('description_project', models.TextField(max_length=10000, verbose_name='description_project')),
                ('date_of_creation', models.DateField(auto_now=True, verbose_name='date_of_creation')),
                ('date_of_update', models.DateField(auto_now_add=True, verbose_name='date_update')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.statusmodel', verbose_name='StatusModel')),
            ],
        ),
    ]
