# Generated by Django 5.1.3 on 2024-11-07 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projectsmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsmodel',
            name='name_project',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='projectsmodel',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.statusmodel', verbose_name='status'),
        ),
    ]
