# Generated by Django 5.1.3 on 2024-11-07 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projectsmodel_name_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsmodel',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.statusmodel', verbose_name='status'),
            preserve_default=False,
        ),
    ]
