# Generated by Django 5.1.3 on 2024-11-06 08:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='age',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='age'),
        ),
    ]
