# Generated by Django 5.1.3 on 2024-11-06 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('users', '0002_alter_usersmodel_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='avatar',
            field=models.FileField(null=True, upload_to='avatar_user'),
        ),
        migrations.AlterField(
            model_name='usersmodel',
            name='dev_stack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.devstackmodel'),
        ),
        migrations.AlterField(
            model_name='usersmodel',
            name='profession_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.professioncategorymodel'),
        ),
        migrations.AlterField(
            model_name='usersmodel',
            name='projects',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectsmodel'),
        ),
        migrations.AlterField(
            model_name='usersmodel',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.rolemodel'),
        ),
    ]
