# Generated by Django 5.1.3 on 2024-11-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projectsmodel_name_project_and_more'),
        ('users', '0003_alter_usersmodel_avatar_alter_usersmodel_dev_stack_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersmodel',
            name='projects',
        ),
        migrations.AddField(
            model_name='usersmodel',
            name='projects',
            field=models.ManyToManyField(to='projects.projectsmodel'),
        ),
    ]
