# Generated by Django 5.1.3 on 2024-11-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_usersmodel_projects_usersmodel_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmodel',
            name='create_projects',
            field=models.BooleanField(default=False),
        ),
    ]
