# Generated by Django 5.1.3 on 2024-11-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_usersmodel_create_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='create_projects',
            field=models.BooleanField(default=True),
        ),
    ]
