# Generated by Django 5.1.3 on 2024-11-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_projectsmodel_status'),
        ('users', '0006_alter_usersmodel_create_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='projects',
            field=models.ManyToManyField(null=True, to='projects.projectsmodel'),
        ),
    ]
