# Generated by Django 5.1.3 on 2024-11-11 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_usersmodel_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='profession_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.professioncategorymodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersmodel',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.rolemodel'),
            preserve_default=False,
        ),
    ]
