# Generated by Django 5.1.3 on 2024-11-11 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0004_alter_projectsmodel_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityTaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_priority', models.CharField(max_length=120, verbose_name='name_priority')),
            ],
        ),
        migrations.CreateModel(
            name='StatusTaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_status', models.CharField(max_length=120, verbose_name='name_status')),
            ],
        ),
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_task', models.CharField(max_length=120, verbose_name='name_task')),
                ('description_task', models.TextField(verbose_name='description_task')),
                ('date_of_creation', models.DateField(auto_now=True, verbose_name='date_of_creation')),
                ('date_of_update', models.DateField(auto_now_add=True, verbose_name='date_of_update')),
                ('date_of_deadline', models.DateField(null=True, verbose_name='date_of_deadline')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executor_task', to=settings.AUTH_USER_MODEL)),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.prioritytaskmodel')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectsmodel')),
                ('resp_for_testing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resp_task', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.statustaskmodel')),
            ],
        ),
    ]
